language: java

sudo: false # faster builds

install: false

jdk:
  - oraclejdk8

notifications:
  email: false

cache:
  directories:
    - '$HOME/.m2'

script:
  - export TZ=Asia/Shanghai
  - mvn clean
